---
abstract: 'Read MaxMind DB files and look up IP addresses'
author:
  - 'Dave Rolsky <drolsky@maxmind.com>'
  - 'Olaf Alders <oalders@maxmind.com>'
build_requires:
  Exporter: '0'
  Path::Class: '0'
  Scalar::Util: '0'
  Test::Bits: '0'
  Test::Fatal: '0'
  Test::MaxMind::DB::Common::Data: '0'
  Test::MaxMind::DB::Common::Util: '0'
  Test::More: '0'
  Test::Number::Delta: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MaxMind-DB-Reader
requires:
  Carp: '0'
  Data::IEEE754: '0'
  Data::Printer: '0'
  Data::Validate::IP: '0.16'
  DateTime: '0'
  Encode: '0'
  Getopt::Long: '0'
  IO::File: '0'
  IO::Handle: '0'
  JSON::PP: '0'
  List::AllUtils: '0'
  Math::Int128: '0'
  MaxMind::DB::Common: '0.031000'
  MaxMind::DB::Metadata: '0'
  MaxMind::DB::Role::Debugs: '0'
  MaxMind::DB::Types: '0'
  Module::Implementation: '0'
  Moo: '1.003000'
  Moo::Role: '0'
  MooX::StrictConstructor: '0'
  Net::Works::Address: '0.12'
  Net::Works::Network: '0'
  Role::Tiny: '1.003002'
  Try::Tiny: '0'
  autodie: '0'
  bytes: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.010000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/maxmind/MaxMind-DB-Reader-perl/issues
  repository: git://github.com/maxmind/MaxMind-DB-Reader-perl.git
version: '0.060001'
x_authority: cpan:MAXMIND
x_contributors:
  - 'Greg Oschwald <goschwald@maxmind.com>'
  - 'Ran Eilam <reilam@maxmind.com>'
  - 'William Stevenson <skyblue@skybluecircles.com>'
