
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
API
CPAN
GeoIP
GeoLite
GitHub
IP
IPv
MaxMind's
OO
VERSIONING
YYY
YYYZZZ
downloadable
libmaxminddb
versioning
Dave
Rolsky
drolsky
Olaf
Alders
oalders
MaxMind
Inc
Greg
Oschwald
goschwald
Ran
Eilam
reilam
William
Stevenson
skyblue
lib
DB
Reader
Decoder
Verifier
Role
HasDecoder
Data
EndMarker
NodeReader
PP
HasMetadata
Container
Sysreader
